helloworld/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^check_login/$', views.check_login, name='check_login'),
]

myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^helloworld/',include('helloworld.urls',namespace="helloworld")),
]

helloworld/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

helloworld/views.py
from django.shortcuts import render
from django.http import HttpResponse
import logging
from django.http import JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404

def index(request):
    #return HttpResponse("Hello World. First Django Project. ThePythonDjango.Com")
    return render(request,"helloworld/index.html",{})



def check_login(request):
    if request.method == "GET":
        raise Http404("URL doesn't exists")
    else:   
        response_data = {}
        login = request.POST["login"]
        user = None
        try:
            try:
                # we are matching the input again hardcoded value to avoid use of DB.
                # You can use DB and fetch value from table and proceed accordingly.
                if login == "rana" or login == "rana1":
                    user = True
            except ObjectDoesNotExist as e:
                pass
            except Exception as e:
                raise e
            if not user:
                response_data["is_success"] = True
            else:
                response_data["is_success"] = False
        except Exception as e:
            response_data["is_success"] = False
            response_data["msg"] = "Some error occurred. Please let Admin know."

        return JsonResponse(response_data)

helloworld/templates/helloworld/index.html
<html>
<head>
{% load staticfiles %}
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script>
function check_login(element) {
	$("#login_ok").hide();
	$("#login_not").hide();
	login = $(element).val();
	if (login == "") {
		return;
	}
	$.ajax({
		url : $(element).attr("data-url"),
		data : {
			"csrfmiddlewaretoken" : $(element).siblings("input[name='csrfmiddlewaretoken']" ).val(),
			"login":login
		},
		method: "POST",
		dataType : "json",
		success : function (data) {
			//console.log(data);
			if (data.is_success) {
				$("#login_ok").show();
			} else {
				$("#login_not").show();
			}
		}
	});
}


</script>


</head>
<body>




<label for="login" class="col-md-2 control-label">Login</label>
<div class="col-md-4">
    <input type="text" class="form-control input-sm" name="login" id="login" placeholder="Login or Username" required="True" maxlength="40" onkeyup="check_login(this);return false;" data-url="{% url "helloworld:check_login" %}"/>
    {% csrf_token %}
</div>
<div class="col-md-6 col-sm-6" style="color:red;display:none;margin-top: 4px;"  id="login_not">
    <span class="glyphicon glyphicon-remove"></span> Username already taken.
</div>
<div class="col-md-6 col-sm-6" style="color: green;display: none;margin-top: 4px;" id="login_ok">
    <span class="glyphicon glyphicon-ok"></span> Username available.
</div>
</body>

</html>